export const CREATE_AUTHOR = "CREATE_AUTHOR";
export const RETRIEVE_AUTHORS = "RETRIEVE_AUTHORS";
export const UPDATE_AUTHOR = "UPDATE_AUTHOR";
export const DELETE_AUTHOR = "DELETE_AUTHOR";
export const DELETE_ALL_AUTHORS = "DELETE_ALL_AUTHORS";

export const CREATE_BOOK = "CREATE_BOOK";
export const RETRIEVE_BOOKS = "RETRIEVE_BOOKS";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";
export const DELETE_ALL_BOOKS = "DELETE_ALL_BOOKS";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_ALL_CATEGORIES = "DELETE_ALL_CATEGORIES";

export const CREATE_PUBLISHER = "CREATE_PUBLISHER";
export const RETRIEVE_PUBLISHERS = "RETRIEVE_PUBLISHERS";
export const UPDATE_PUBLISHER = "UPDATE_PUBLISHER";
export const DELETE_PUBLISHER = "DELETE_PUBLISHER";
export const DELETE_ALL_PUBLISHERS = "DELETE_ALL_PUBLISHERS";